import React from 'react';
import { createRoot } from 'react-dom/client';
import html2pdf from 'html2pdf.js';
import { Vocabulary, GrammarNote, User } from '../types';

interface PdfProps {
  type: 'vocabulary' | 'grammar';
  data: any[];
  user: User | null;
}

const PdfTemplate: React.FC<PdfProps> = ({ type, data, user }) => {
  const dateOptions: Intl.DateTimeFormatOptions = { year: 'numeric', month: 'long', day: 'numeric' };
  const formattedDate = new Date().toLocaleDateString('en-US', dateOptions);

  return (
    <div id="pdf-content" className="bg-white text-black" style={{ width: '100%', padding: '20px', fontFamily: "'Times New Roman', 'Kalpurush', serif", boxSizing: 'border-box' }}>
      <style>{`
        @import url('https://fonts.maateen.me/kalpurush/font.css');
        .pdf-font { font-family: 'Times New Roman', 'Kalpurush', serif !important; }
        .avoid-break { page-break-inside: avoid; }
        
        .pdf-title-container { text-align: center; margin-bottom: 30px; }
        .pdf-title { 
          font-size: 28px; 
          font-weight: bold; 
          color: #254b94; 
          text-transform: uppercase; 
          letter-spacing: 0.05em; 
          text-decoration: underline;
          text-underline-offset: 6px;
          margin-bottom: 8px;
        }
        .pdf-subtitle {
          font-size: 10px;
          color: #6b7280;
          text-transform: uppercase;
          letter-spacing: 0.1em;
        }

        .pdf-directions {
          border: 1px solid #6b7280;
          border-radius: 8px;
          padding: 16px;
          margin-bottom: 30px;
        }
        .pdf-directions-title {
          font-size: 11px;
          font-weight: bold;
          color: #254b94;
          text-transform: uppercase;
          margin-bottom: 8px;
        }
        .pdf-directions-text {
          font-size: 13px;
          color: #374151;
          line-height: 1.5;
        }

        .pdf-table { width: 100%; border-collapse: collapse; margin-bottom: 40px; }
        .pdf-table th, .pdf-table td { border: 1px solid #e5e7eb; padding: 12px 16px; text-align: left; font-size: 13px; }
        .pdf-table th { 
          background-color: #254b94; 
          color: white; 
          font-weight: bold; 
          text-transform: uppercase; 
          font-size: 10px; 
          letter-spacing: 0.05em; 
        }
        
        .pdf-footer {
          display: flex;
          justify-content: space-between;
          border-top: 1px solid #e5e7eb;
          padding-top: 16px;
          font-size: 10px;
          color: #9ca3af;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }
      `}</style>

      <div className="pdf-title-container">
        <div className="pdf-title pdf-font">
          {type === 'vocabulary' ? 'VOCABULARY WORKSHEET' : 'GRAMMAR WORKSHEET'}
        </div>
        <div className="pdf-subtitle pdf-font">GENERATED BY LINGUISTAI</div>
      </div>

      <div className="pdf-directions pdf-font">
        <div className="pdf-directions-title">DIRECTIONS:</div>
        <div className="pdf-directions-text">
          <strong>User:</strong> {user?.name || 'Scholar'} <br/>
          <strong>Date:</strong> {formattedDate} <br/>
          <strong>Total Items:</strong> {data.length} {type === 'vocabulary' ? 'words' : 'notes'} <br/>
          <br/>
          Review the {type === 'vocabulary' ? 'vocabulary list' : 'grammar notes'} below carefully. Memorize the meanings and practice the pronunciation of each term. Use the context sentences to understand how to apply these words in daily conversation.
        </div>
      </div>

      <table className="pdf-table pdf-font">
        <thead>
          <tr>
            {type === 'vocabulary' ? (
              <>
                <th style={{ width: '25%' }}>VOCABULARY TERM</th>
                <th style={{ width: '30%' }}>MEANING (DEFINITION)</th>
                <th style={{ width: '45%' }}>CONTEXTUAL ILLUSTRATION</th>
              </>
            ) : (
              <>
                <th style={{ width: '25%' }}>TOPIC</th>
                <th style={{ width: '30%' }}>FORMULA</th>
                <th style={{ width: '45%' }}>NOTES</th>
              </>
            )}
          </tr>
        </thead>
        <tbody>
          {data.map((item, index) => (
            <tr key={item.id || index} className="avoid-break">
              {type === 'vocabulary' ? (
                <>
                  <td style={{ fontWeight: 'bold', color: '#111827' }}>{item.word}</td>
                  <td style={{ color: '#374151' }}>{item.meaning}</td>
                  <td style={{ color: item.example ? '#374151' : '#9ca3af', fontStyle: item.example ? 'normal' : 'italic' }}>
                    {item.example || 'No example provided.'}
                  </td>
                </>
              ) : (
                <>
                  <td style={{ fontWeight: 'bold', color: '#111827' }}>{item.topic}</td>
                  <td style={{ color: '#374151' }}>{item.formula}</td>
                  <td style={{ color: '#374151' }}>{item.notes}</td>
                </>
              )}
            </tr>
          ))}
        </tbody>
      </table>

      <div className="pdf-footer pdf-font avoid-break">
        <div>LINGUISTAI</div>
        <div>Date: {formattedDate}</div>
      </div>
    </div>
  );
};

export const exportToPdf = async (type: 'vocabulary' | 'grammar', data: any[], user: User | null) => {
  if (!data || data.length === 0) {
    alert('No data to export.');
    return;
  }

  // Create a temporary container
  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.style.width = '800px';
  document.body.appendChild(container);

  const root = createRoot(container);
  
  // Render the component
  root.render(<PdfTemplate type={type} data={data} user={user} />);

  // Wait for render and fonts to load
  await new Promise(resolve => setTimeout(resolve, 1500));

  const element = container.querySelector('#pdf-content');
  
  if (element) {
    const opt = {
      margin:       [15, 15, 15, 15],
      filename:     `LinguistAI_${type}_${new Date().getTime()}.pdf`,
      image:        { type: 'jpeg', quality: 1 },
      html2canvas:  { scale: 2, useCORS: true, letterRendering: true, windowWidth: 800 },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
    };

    try {
      await html2pdf().set(opt).from(element).save();
    } catch (err) {
      console.error('PDF generation failed:', err);
      alert('Failed to generate PDF. Please try again.');
    }
  }

  // Cleanup
  setTimeout(() => {
    root.unmount();
    document.body.removeChild(container);
  }, 1000);
};
